name: aeson-streaming-conduit
version: 0.0.0.0
license: PublicDomain

library:
  source-dirs: src
  dependencies:
    - base
    - attoparsec
    - conduit
    - aeson
    - aeson-streaming
    - bytestring
  ghc-options: -Wall -Wincomplete-uni-patterns -Wpartial-fields -Wincomplete-record-updates -Wmissing-export-lists -Wcompat -O
